#!/bin/sh
set -euo pipefail

# there is intentionally no store subcommand support.
# I don't want git messing with my password database.
if [ "$1" == "get" ]; then
  USERNAME="$(sed -nu 's/username=//p' | head -n1)"
  PASSWORD="$(lpass show "${USERNAME}" --pass </dev/tty)"

  printf "username=%s\npassword=%s\n" "${USERNAME}" "${PASSWORD}"
fi
