#!/bin/sh
set -exuo pipefail

GUIX="${GUIX:-guix}"
GUIX_REPO_LOCATION="${GUIX_REPO_LOCATION:-${HOME}/git/guix}"
EXTRA_AUTHORIZATIONS="${EXTRA_AUTHORIZATIONS:-${HOME}/git/mguix/.guix-authorizations}"

cd "${GUIX_REPO_LOCATION}"

git -C "${GUIX_REPO_LOCATION}" fetch upstream

TMPDIR="$(mktemp -d)"
git -C "${GUIX_REPO_LOCATION}" worktree add "${TMPDIR}" keyring

git -C "${TMPDIR}" rebase upstream/keyring --no-gpg-sign

git -C "${TMPDIR}" checkout upstream/master

if ! "${GUIX}" git authenticate --historical-authorizations="${EXTRA_AUTHORIZATIONS}" --repository="${TMPDIR}" --cache-key=guix-git \
  "c91e27c60864faa229198f6f0caf620275c429a2" "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA"
  #$("${GUIX}" describe --format=json | jq -r '.[] | select(.name == "guix").introduction | "\(.commit) \(.signer | gsub(" "; ""))"')
then
  printf 'AUTHORIZATION FAILED!\n'
  exit 1
fi

git -C "${GUIX_REPO_LOCATION}" worktree remove "${TMPDIR}"

# TODO: this is a hack so update-guix-package doesn't make merge conflicts
git -C "${GUIX_REPO_LOCATION}" restore gnu/packages/package-management.scm

if [ "$(git -C "${GUIX_REPO_LOCATION}" status -s | wc -c)" != "1" ] \
   && LANG=C LC_ALL=C git -C "${GUIX_REPO_LOCATION}" stash save | grep -Fxv 'No local changes to save'; then
  STASHED=1
else
  STASHED=0
fi

git -C "${GUIX_REPO_LOCATION}" rebase upstream/master

WIP_HEAD="$(git -C "${GUIX_REPO_LOCATION}" rev-parse HEAD)"
if [ "${STASHED}" == "1" ] && [ "$(git -C "${GUIX_REPO_LOCATION}" stash list | wc -l)" != "0" ]; then
  WIP_HEAD="$(git -C "${GUIX_REPO_LOCATION}" rev-parse stash@{0})"
  git -C "${GUIX_REPO_LOCATION}" stash pop
fi

# TODO: --without-tests=guile@3.0.7 --without-tests=guix is temporary
GUIX_ENVIRONMENT="${GUIX} environment --pure guix --ad-hoc guile-semver" # --without-tests=guile@3.0.7 --with-debug-info=libgit2 --with-debug-info=guile-git" # TODO
GUIX_CONTAINER="${GUIX_ENVIRONMENT} --container --link-profile"

if [ ! -f "${GUIX_REPO_LOCATION}/Makefile" ]; then
  ${GUIX_CONTAINER} -- ./bootstrap
  ${GUIX_CONTAINER} -- ./configure --localstatedir=/var --prefix="${HOME}/.local"
  ${GUIX_CONTAINER} -- make clean
fi

#pushd doc
## HACK: localized docs break build for some reason, make them all English
#find . -type f -name 'contributing.*.texi' -exec cp -v contributing.texi {} \;
#find . -type f -name 'guix-cookbook.*.texi' -exec cp -v guix-cookbook.texi {} \;
#find . -type f -name 'guix.*.texi' -exec cp -v guix.texi {} \;
#find . -type f -name 'guix.*.texi' -exec cp -v guix.texi {} \;
#find . -type f -name 'version-*.texi' -exec cp -v version.texi {} \;
#popd

if ! ${GUIX_CONTAINER} -- make -j"$(nproc)"; then
  ${GUIX_CONTAINER} -- make clean
  ${GUIX_CONTAINER} -- make -j"$(nproc)"
fi

#${GUIX_CONTAINER} -- make check

#"${GUIX}" environment --pure guix -- make install
${GUIX_CONTAINER} --ad-hoc coreutils git --share=/var/guix/daemon-socket/socket -- env \
    GUILE_AUTO_COMPILE=0 GUIX_ALLOW_ME_TO_USE_PRIVATE_COMMIT=true \
    ./pre-inst-env guile build-aux/update-guix-package.scm "${WIP_HEAD}"
#${GUIX_CONTAINER} --ad-hoc coreutils git --share=/var/guix/daemon-socket/socket -- env \
#    GUILE_AUTO_COMPILE=0 GUIX_ALLOW_ME_TO_USE_PRIVATE_COMMIT=true \
#    make update-NEWS

# TODO: --without-tests=guile@3.0.7 --without-tests=guix is temporary
#${GUIX_ENVIRONMENT} -- ./pre-inst-env guix install --without-tests=guile@3.0.7 --without-tests=guix guix
${GUIX_ENVIRONMENT} -- ./pre-inst-env guix install --without-tests=guix guix

# upgrade root as well for guix-daemon's sake
# TODO: --without-tests=guile@3.0.7 --without-tests=guix is temporary
#sudo ${GUIX_ENVIRONMENT} -- ./pre-inst-env guix install --without-tests=guile@3.0.7 --without-tests=guix guix
sudo ${GUIX_ENVIRONMENT} -- ./pre-inst-env guix install --without-tests=guix guix
#sudo rc-service guix-daemon restart
sudo killall -SIGINT guix-daemon || :
sudo rc-service guix-daemon zap
sudo rc-service guix-daemon start

git -C "${GUIX_REPO_LOCATION}" worktree prune
rm "${GUIX_REPO_LOCATION}/"*-checkout
