#!/bin/sh
# play?: print metadata for what mpv is playing
set -euo pipefail

MPV_PID="${MPV_PID-$(
  for p in $(pgrep -u ${UID} mpv); do
    find /proc/${p}/task/${p}/fd -type l -exec readlink '{}' + | \
    grep -Fxq "$(
      grep ~/.config/mpv/socket /proc/net/unix | cut -d' ' -f7 | \
      sed 's/^\(.*\)$/socket:[\1]/'
    )" && printf '%s\n' "${p}" || :
  done
)}"

# TODO: reinstate this (currently broken) check
#if printf "%s" "${MPV_PID}" | grep -q $'\n'; then
#  printf "error: multiple mpv's seem to have the socket open:\n%s\n" "${MPV_PID}"
#  exit 1
#fi
MPV_PID="$(printf '%s' "${MPV_PID}" | head -n1)"

if [ ! -z "${MPV_PID}" ]; then
  cd /proc/${MPV_PID}/cwd
fi

MEDIA_PATH="$(
  printf '{ "command": ["get_property", "path"] }\n' | nc -Uw 1 ~/.config/mpv/socket | \
  (
    head -n1 | jq -r '.data'
    dd iflag=nonblock status=none &>/dev/null &
  )
)"
if [ -e "${MEDIA_PATH}" ]; then
  MEDIA_PATH="$(realpath -s "${MEDIA_PATH}")"
fi
printf "Path: %s\n" "${MEDIA_PATH}"

printf '{ "command": ["get_property", "filtered-metadata"] }\n' | nc -Uw 1 ~/.config/mpv/socket | \
(
  head -n1 | jq -r '.data | keys_unsorted[] as $k | "\($k): \(.[$k])"'
  dd iflag=nonblock status=none &>/dev/null &
)
