#!/bin/sh
# play?: print metadata for what mpv is playing
set -euo pipefail

TMPFILE="$(mktemp -ut mpv-pid.XXXXX)"
mkfifo "${TMPFILE}"
trap 'rm -f "${TMPFILE}"' EXIT
jq -cn '{"command":["run", "bash", "-c", "echo $PPID > " + $ARGS.positional[0]]}' --args "${TMPFILE}" | \
nc -Uw 1 ~/.config/mpv/socket | head -n1 >/dev/null
MPV_PID="$(cat "${TMPFILE}")"
rm -f "${TMPFILE}"

if [ ! -z "${MPV_PID}" ]; then
  cd /proc/${MPV_PID}/cwd
fi

MEDIA_PATH="$(printf '{ "command": ["get_property", "path"] }\n' | nc -Uw 1 ~/.config/mpv/socket | head -n1 | jq -r '.data')"
if [ -e "${MEDIA_PATH}" ]; then
  MEDIA_PATH="$(realpath -s "${MEDIA_PATH}")"
fi
printf "Path: %s\n" "${MEDIA_PATH}"

printf '{ "command": ["get_property", "filtered-metadata"] }\n' | nc -Uw 1 ~/.config/mpv/socket | \
head -n1 | jq -r '.data | keys_unsorted[] as $k | "\($k): \(.[$k])"'
