#!/bin/bash
set -o pipefail

cd ~/media/music
SELECTED="$(find ! \( -type f -name 'cover.*' \) ! -path '*/.*' -print0 | fzf --read0 --print0 --filter "$(tr '-' '!' <<<"$*")" | cut -d '' -f1)"
if [[ -z "${SELECTED}" ]]; then
  echo "No music matches the query '$*'."
  exit 1
fi

if [[ "${SELECTED}" == '.' ]]; then
  SORT=shuf
else
  SORT=sort
fi

# TODO: will fail with newlines in filenames
exec mpv --idle --loop-playlist --input-file=<(
    find -L "${SELECTED}" -type f ! -path '*/.*' -print0 | ${SORT} -z | \
    xargs -0n32 file --mime-type --no-pad | grep -Po '^.*(?=: (audio|video)/[0-9a-z-]*$)' | \
    xargs -n32 jq -cn '$ARGS.positional[] | { "command": ["loadfile", ., "append-play"] }' --args
)
