#!/bin/sh
# switch_focus: alt-tab for sway

WINDOWS="$(swaymsg -t get_tree | jq -c '[while(.focused == false; .nodes[]?) | select(.type == "workspace" and .focus != [])][0] | recurse(.nodes[]?) | select(.nodes == []) | [.id, .focused]')"

[ "$1" = "-r" ] && WINDOWS="$(tac <<< "${WINDOWS}")"

ID="$((echo "${WINDOWS}" && echo "${WINDOWS}") | grep -A2 '\[[0-9]*,true\]' | head -n2 | tail -n1 | cut -d, -f1 | tail -c+2)"

swaymsg "[con_id=${ID}]" focus >/dev/null
