#!/bin/sh
# Unsets some Wayland-exclusive environment variables and ensures DISPLAY (X11)
# is set for the application. (This won't stop it from using Wayland if that's
# the default.) This magically works with 'swaymsg exec', but not if you want
# stdout/stderr to go to your terminal instead of sway.

unset GDK_BACKEND
unset QT_QPA_PLATFORM
unset CLUTTER_BACKEND
unset SDL_VIDEODRIVER
unset EWOL_BACKEND

if [ -z "${DISPLAY+x}" ]; then
    TMPFILE="$(mktemp -u)"
    mkfifo "${TMPFILE}"
    swaymsg exec 'sleep 1 && printf %s "${DISPLAY}" > "'"${TMPFILE}"'"'
    read -r DISPLAY < "${TMPFILE}"
    export DISPLAY
    rm "${TMPFILE}"
fi

exec "$@"
