#!/bin/sh

/usr/libexec/xdg-desktop-portal -rv &
PORTAL1=$!
/usr/libexec/xdg-desktop-portal-gtk -rv &
PORTAL2=$!

#pulseaudio -k
#pulseaudio --verbose &
#PULSEAUDIO=$!

#exec flatpak run us.zoom.Zoom
flatpak run us.zoom.Zoom "$@"

kill -s INT "${PORTAL1}" "${PORTAL2}" #"${PULSEAUDIO}"
